### ISSUE TITLE
NosuchMethodError with autocompleteSupportFragment

### ISSUE THREAD

**Issue by YoungbinHa** [KelvinPac/EasyLocationPicker#7]
I got this error when I try to implement it. I used in my fragment 

2020-12-06 01:54:13.761 22563-22563/com.example.restroomapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.restroomapp, PID: 22563
    java.lang.NoSuchMethodError: No virtual method setCountry(Ljava/lang/String;)V in class Lcom/google/android/libraries/places/widget/AutocompleteSupportFragment; or its super classes (declaration of 'com.google.android.libraries.places.widget.AutocompleteSupportFragment' appears in /data/app/com.example.restroomapp-2/base.apk)
        at com.loginext.easylocationpicker.EasyLocationPickerActivity.onCreate(EasyLocationPickerActivity.java:129)
        at android.app.Activity.performCreate(Activity.java:6955)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6836)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by KelvinPac** [comment]
which version are you using?

**Comment by KelvinPac** [comment]
Try this version implementation
'com.github.KelvinPac:EasyLocationPicker:v.1.1.1'

If you get the same error, then try adding the latest google places library
in your build.gradle

implementation 'com.google.android.libraries.places:places:xxx'
